### ISSUE TITLE
response.parsedGraph() (method) & resource.parsedGraph (property) seems confusing

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-web-client#8]
I found it confusing that response has `.parsedGraph()` method and resource has `.parsedGraph` property.

When `client.get()` resolves with container and when it resolves with response seems inconsistent especially that those two use the same key for method and property.

For consistency get could always resolve with a resource/container

**Comment by dan-f** [comment]
I just ran into this as well, and I'm going to consider it a bug. I'm gonna assign this to myself and fix it.

**Comment by dan-f** [comment]
Yeah the problem here is that the `SolidResponse` and `SolidContainer` objects are being promised by `client.solidRequest,` yet they do not expose the same interface to the caller. I don't know why those two classes are being used interchangeably because one represents the HTTP response (with additional data), while the other represents a solid container. Two pretty different things.

**Comment by dmitrizagidulin** [comment]
Yeah, agreed. `SolidResponse` should instead have a `.resource` property, that would contain either a `SolidResource` or `SolidContainer`.

**Comment by dmitrizagidulin** [comment]
Happy to fix this, if you'd like.

**Comment by dan-f** [comment]
I've already been looking at it, and I'm blocked on this, so I'll continue.

**Comment by dan-f** [comment]
Addressed by #17
